apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alternative-credit-scoring-dev
  annotations: {platform.finance2/state: PENDING_VALIDATION}
spec:
  project: default
  source:
    repoURL: https://github.com/red-hat-nella/finance.git
    targetRevision: main
    path: deploy/openshift/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: rh-ee-mpolo-dev
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions: [CreateNamespace=false, RespectIgnoreDifferences=true]
