secrets:
  postgres_admin_password:
    external: true
    name: postgres_admin_password
  postgres_password:
    external: true
    name: postgres_password
  postgres_retention_password:
    external: true
    name: postgres_retention_password
  scoring_service_token:
    external: true
    name: scoring_service_token
  pii_encryption_key:
    external: true
    name: pii_encryption_key
  pii_hmac_key:
    external: true
    name: pii_hmac_key
