apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [serviceaccounts.yaml,frontend-configmap.yaml,ingestion-configmap.yaml,scoring-configmap.yaml,frontend-deployment.yaml,frontend-service.yaml,frontend-route.yaml,ingestion-deployment.yaml,ingestion-service.yaml,scoring-deployment.yaml,scoring-service.yaml,postgres-pvc.yaml,postgres-service.yaml,postgres-statefulset.yaml,networkpolicies.yaml]

