apiVersion: v1
kind: Secret
metadata: {name: scoring-secrets}
type: Opaque
stringData:
  database-password: REPLACE_USING_CREATE_SECRETS_SCRIPT
  pii-encryption-key: REPLACE_USING_CREATE_SECRETS_SCRIPT
  pii-hmac-key: REPLACE_USING_CREATE_SECRETS_SCRIPT
  scoring-service-token: REPLACE_USING_CREATE_SECRETS_SCRIPT

