apiVersion: v1
kind: ServiceAccount
metadata: {name: frontend}
---
apiVersion: v1
kind: ServiceAccount
metadata: {name: ingestion}
---
apiVersion: v1
kind: ServiceAccount
metadata: {name: scoring}
---
apiVersion: v1
kind: ServiceAccount
metadata: {name: database-jobs}

