import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
import YAML from 'yaml';

const publicContract = 'specs/003-accept-terms/contracts/terms-public-v1.openapi.yaml';
const internalContract = 'specs/003-accept-terms/contracts/terms-access-internal-v1.openapi.yaml';
const publicTypes = 'apps/terms-web/src/app/core/api/generated/terms-public.ts';
const internalTypes = 'services/ingestion/src/clients/generated/terms-access.ts';

async function load(file) {
  return YAML.parse(await readFile(file, 'utf8'));
}

function assertProblemExample(api, expectedCode) {
  const problem = api.components.schemas.Problem;
  assert.ok(Array.isArray(problem.required));
  for (const field of ['type', 'title', 'status', 'code', 'retryable']) {
    assert.ok(problem.required.includes(field), `Problem requires ${field}`);
  }
  assert.ok(problem.examples?.length > 0, 'RFC 9457 Problem must include a synthetic example');
  const example = problem.examples[0];
  assert.doesNotThrow(() => new URL(example.type));
  assert.equal(example.code, expectedCode);
  assert.ok(example.status >= 400 && example.status <= 599);
  assert.equal(typeof example.title, 'string');
  assert.equal(typeof example.retryable, 'boolean');
  assert.match(example.requestId, /^[0-9a-f-]{36}$/i);
}

test('terms public v1 is the generated terms-web boundary', async () => {
  const api = await load(publicContract);
  assert.equal(api.openapi, '3.1.0');
  assert.equal(api.info.version, '1.0.0');
  assert.equal(api.servers[0].url, '/terms-api');
  assert.deepEqual(api.security, [{ bearerAuth: [] }]);
  assert.equal(api.paths['/v1/current'].get.operationId, 'getCurrentTerms');
  assert.equal(api.paths['/v1/acceptances'].post.operationId, 'acceptCurrentTerms');
  assert.equal(
    api.paths['/v1/acceptances'].post.responses['409'].$ref,
    '#/components/responses/Conflict',
  );
  assertProblemExample(api, 'TERMS_VERSION_CHANGED');

  const generated = await readFile(publicTypes, 'utf8');
  assert.match(generated, /operations\["getCurrentTerms"\]/);
  assert.match(generated, /operations\["acceptCurrentTerms"\]/);
  assert.match(generated, /"application\/problem\+json"/);
});

test('terms internal v1 is minimal, dual-authenticated and generated for ingestion', async () => {
  const api = await load(internalContract);
  const decision = api.paths['/internal/v1/access-decisions'].post;
  assert.equal(api.openapi, '3.1.0');
  assert.equal(api.info.version, '1.0.0');
  assert.deepEqual(api.security, [{ bearerAuth: [], serviceToken: [] }]);
  assert.equal(api.components.securitySchemes.serviceToken.name, 'X-Service-Token');
  assert.equal(decision.operationId, 'decideTermsAccess');
  assert.match(decision.description, /500 ms/);
  assert.deepEqual(api.components.schemas.AccessDecision.properties.reason.enum, [
    'ACCEPTED',
    'ACCEPTANCE_REQUIRED',
    'NO_EFFECTIVE_VERSION',
  ]);
  assert.doesNotMatch(
    JSON.stringify(api.components.schemas.AccessDecision),
    /content|markdown|documentSha|contentSha/i,
  );
  assertProblemExample(api, 'TERMS_SERVICE_UNAVAILABLE');

  const generated = await readFile(internalTypes, 'utf8');
  assert.match(generated, /operations\["decideTermsAccess"\]/);
  assert.match(generated, /"application\/problem\+json"/);
});

test('producer/consumer ownership and generated-only boundaries are explicit', async () => {
  const readme = await readFile('specs/003-accept-terms/contracts/README.md', 'utf8');
  assert.match(readme, /terms-public-v1\.openapi\.yaml[^\n]*terms-api[^\n]*terms-web/);
  assert.match(readme, /terms-access-internal-v1\.openapi\.yaml[^\n]*terms-api[^\n]*ingestion/);

  for (const generatedPath of [publicTypes, internalTypes]) {
    const generated = await readFile(generatedPath, 'utf8');
    assert.match(generated, /This file was auto-generated by openapi-typescript/);
    assert.match(generated, /export interface paths/);
  }
});
