apiVersion: v1
kind: ServiceAccount
metadata: {name: migrations, labels: {app.kubernetes.io/part-of: alternative-credit-scoring}}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata: {name: retention, labels: {app.kubernetes.io/part-of: alternative-credit-scoring}}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata: {name: reconciler, labels: {app.kubernetes.io/part-of: alternative-credit-scoring}}
automountServiceAccountToken: false
