apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: alternative-scoring-dev
resources: [../../base]
images:
  - name: image-registry.openshift-image-registry.svc:5000/alternative-scoring/frontend
    newName: image-registry.openshift-image-registry.svc:5000/alternative-scoring-dev/frontend
    newTag: 1.0.0
  - name: image-registry.openshift-image-registry.svc:5000/alternative-scoring/ingestion
    newName: image-registry.openshift-image-registry.svc:5000/alternative-scoring-dev/ingestion
    newTag: 1.0.0
  - name: image-registry.openshift-image-registry.svc:5000/alternative-scoring/scoring
    newName: image-registry.openshift-image-registry.svc:5000/alternative-scoring-dev/scoring
    newTag: 1.0.0
patches:
  - target: {kind: ConfigMap, name: ingestion-config}
    patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata: {name: ingestion-config}
      data:
        NODE_ENV: development
        DATABASE_SSL_MODE: disable
